/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/core/core.module';
import * as i2 from '@angular/common';
import * as i3 from '../../../../src/app/core/engine/keyboard-engine.service';
import * as i4 from '../../../../src/app/core/engine/timer-engine.service';
import * as i5 from '../../../../src/app/core/apm-test/apm-test.service';
import * as i6 from '../../../../src/app/core/keyboard/keyboard-mapping.service';
export const CoreModuleNgFactory:i0.NgModuleFactory<i1.CoreModule> = i0.ɵcmf(i1.CoreModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.KeyboardEngineService,
          i3.KeyboardEngineService,([] as any[])),i0.ɵmpd(4608,i4.TimerEngineService,
          i4.TimerEngineService,([] as any[])),i0.ɵmpd(4608,i5.ApmTestService,i5.ApmTestService,
          [i3.KeyboardEngineService,i4.TimerEngineService]),i0.ɵmpd(4608,i6.KeyboardMappingService,
          i6.KeyboardMappingService,([] as any[])),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,
          ([] as any[])),i0.ɵmpd(512,i1.CoreModule,i1.CoreModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3Zhci93d3cvYXBtL3NyYy9hcHAvY29yZS9jb3JlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy92YXIvd3d3L2FwbS9zcmMvYXBwL2NvcmUvY29yZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
