/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.toolbar__title[_ngcontent-%COMP%]{\n    margin: 0px 15px;\n}\nmat-sidenav[_ngcontent-%COMP%] {\n    width: 350px;\n}\n.mat-sidenav__title[_ngcontent-%COMP%] {\n    background-color: lightslategray;\n    font-size: 1.2em;\n    padding: 1.5em;\n}\n.test-list-box__section-title[_ngcontent-%COMP%] {\n    background-color: lightcoral;\n    padding: 1.5em;\n    font-size: 1em;\n}\n.test-lis-box__section-content[_ngcontent-%COMP%] {\n    padding: 0.4em;\n}\nmat-card[_ngcontent-%COMP%]{\n    margin: 0.5em 0;\n}\n.search-bo[_ngcontent-%COMP%], .test-list-box__section-content[_ngcontent-%COMP%]{\n    padding: 20px;\n}'];
//# sourceMappingURL=homepage.component.css.shim.ngstyle.js.map