/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.toolbar__title[_ngcontent-%COMP%]{\n    margin: 0px 15px;\n}\nmat-sidenav[_ngcontent-%COMP%] {\n    width: 350px;\n}\n.mat-sidenav__title[_ngcontent-%COMP%] {\n    background-color: lightslategray;\n    font-size: 1.2em;\n    padding: 1.5em;\n}\n.test-list-box__section-title[_ngcontent-%COMP%] {\n    background-color: lightcoral;\n    padding: 1.5em;\n    font-size: 1em;\n}\n.test-lis-box__section-content[_ngcontent-%COMP%] {\n    padding: 0.4em;\n}\nmat-card[_ngcontent-%COMP%]{\n    margin: 0.5em 0;\n}\n.search-bo[_ngcontent-%COMP%], .test-list-box__section-content[_ngcontent-%COMP%]{\n    padding: 20px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3Zhci93d3cvYXBtL3NyYy9hcHAvYXBtL2hvbWVwYWdlL2hvbWVwYWdlLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vdmFyL3d3dy9hcG0vc3JjL2FwcC9hcG0vaG9tZXBhZ2UvaG9tZXBhZ2UuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
