/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './luncher.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../node_modules/@angular/material/button/typings/index.ngfactory';
import * as i3 from '@angular/material/core';
import * as i4 from '@angular/material/button';
import * as i5 from '@angular/cdk/platform';
import * as i6 from '@angular/cdk/a11y';
import * as i7 from '@angular/flex-layout/flexbox/api/layout';
import * as i8 from '@angular/flex-layout/media-query/media-monitor';
import * as i9 from '@angular/flex-layout/flexbox/api/layout-align';
import * as i10 from '@angular/common';
import * as i11 from '../../../../../../src/app/apm/apm-exercice/luncher/luncher.component';
const styles_LuncherComponent:any[] = [i0.styles];
export const RenderType_LuncherComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_LuncherComponent,data:{}});
function View_LuncherComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),4,'button',[['class',
      'mat-raised-button'],['color','primary'],['mat-raised-button','']],[[8,'disabled',
      0]],[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:any = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.lunchKeyboardEngine()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },i2.View_MatButton_0,i2.RenderType_MatButton)),i1.ɵdid(1,16384,(null as any),0,
      i3.MatPrefixRejector,([] as any[]),(null as any),(null as any)),i1.ɵdid(2,180224,
      (null as any),0,i4.MatButton,[i1.Renderer2,i1.ElementRef,i5.Platform,i6.FocusMonitor],
      {color:[0,'color']},(null as any)),i1.ɵdid(3,16384,(null as any),0,i4.MatRaisedButtonCssMatStyler,
      ([] as any[]),(null as any),(null as any)),(_l()(),i1.ɵted(-1,0,['Lunch Keyboard Core']))],
      (_ck,_v) => {
        const currVal_1:any = 'primary';
        _ck(_v,2,0,currVal_1);
      },(_ck,_v) => {
        const currVal_0:any = (i1.ɵnov(_v,2).disabled || (null as any));
        _ck(_v,0,0,currVal_0);
      });
}
function View_LuncherComponent_2(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n    '])),(_l()(),i1.ɵeld(1,
      0,(null as any),(null as any),4,'button',[['class','mat-raised-button'],['color',
          'accent'],['mat-raised-button','']],[[8,'disabled',0]],[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.lunchKeyboardEngine()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },i2.View_MatButton_0,i2.RenderType_MatButton)),i1.ɵdid(2,16384,(null as any),
      0,i3.MatPrefixRejector,([] as any[]),(null as any),(null as any)),i1.ɵdid(3,
      180224,(null as any),0,i4.MatButton,[i1.Renderer2,i1.ElementRef,i5.Platform,
          i6.FocusMonitor],{color:[0,'color']},(null as any)),i1.ɵdid(4,16384,(null as any),
      0,i4.MatRaisedButtonCssMatStyler,([] as any[]),(null as any),(null as any)),
      (_l()(),i1.ɵted(-1,0,['Stop Keyboard Core'])),(_l()(),i1.ɵted(-1,(null as any),
          ['\n  ']))],(_ck,_v) => {
    const currVal_1:any = 'accent';
    _ck(_v,3,0,currVal_1);
  },(_ck,_v) => {
    const currVal_0:any = (i1.ɵnov(_v,3).disabled || (null as any));
    _ck(_v,1,0,currVal_0);
  });
}
export function View_LuncherComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),8,'div',[['class',
      'luncher-box'],['fxLayout','column'],['fxLayoutAlign','center center']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),i1.ɵdid(1,737280,(null as any),
      0,i7.LayoutDirective,[i8.MediaMonitor,i1.ElementRef,i1.Renderer],{layout:[0,
          'layout']},(null as any)),i1.ɵdid(2,737280,(null as any),0,i9.LayoutAlignDirective,
      [i8.MediaMonitor,i1.ElementRef,i1.Renderer,[2,i7.LayoutDirective]],{align:[0,
          'align']},(null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),
      i1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_LuncherComponent_1)),
      i1.ɵdid(5,16384,(null as any),0,i10.NgIf,[i1.ViewContainerRef,i1.TemplateRef],
          {ngIf:[0,'ngIf'],ngIfElse:[1,'ngIfElse']},(null as any)),(_l()(),i1.ɵted(-1,
          (null as any),['\n  '])),(_l()(),i1.ɵand(0,[['stop_button',2]],(null as any),
          0,(null as any),View_LuncherComponent_2)),(_l()(),i1.ɵted(-1,(null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i11.LuncherComponent = _v.component;
    const currVal_0:any = 'column';
    _ck(_v,1,0,currVal_0);
    const currVal_1:any = 'center center';
    _ck(_v,2,0,currVal_1);
    const currVal_2:boolean = !_co.trigger;
    const currVal_3:any = i1.ɵnov(_v,7);
    _ck(_v,5,0,currVal_2,currVal_3);
  },(null as any));
}
export function View_LuncherComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-apm-luncher',
      ([] as any[]),(null as any),(null as any),(null as any),View_LuncherComponent_0,
      RenderType_LuncherComponent)),i1.ɵdid(1,49152,(null as any),0,i11.LuncherComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const LuncherComponentNgFactory:i1.ComponentFactory<i11.LuncherComponent> = i1.ɵccf('app-apm-luncher',
    i11.LuncherComponent,View_LuncherComponent_Host_0,{},{isTrigger:'isTrigger'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3Zhci93d3cvYXBtL3NyYy9hcHAvYXBtL2FwbS1leGVyY2ljZS9sdW5jaGVyL2x1bmNoZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL3Zhci93d3cvYXBtL3NyYy9hcHAvYXBtL2FwbS1leGVyY2ljZS9sdW5jaGVyL2x1bmNoZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vdmFyL3d3dy9hcG0vc3JjL2FwcC9hcG0vYXBtLWV4ZXJjaWNlL2x1bmNoZXIvbHVuY2hlci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL3Zhci93d3cvYXBtL3NyYy9hcHAvYXBtL2FwbS1leGVyY2ljZS9sdW5jaGVyL2x1bmNoZXIuY29tcG9uZW50LnRzLkx1bmNoZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGZ4TGF5b3V0PVwiY29sdW1uXCIgZnhMYXlvdXRBbGlnbj1cImNlbnRlciBjZW50ZXJcIiBjbGFzcz1cImx1bmNoZXItYm94XCI+XG4gIDxidXR0b24gbWF0LXJhaXNlZC1idXR0b24gY29sb3I9XCJwcmltYXJ5XCIgKGNsaWNrKT1cImx1bmNoS2V5Ym9hcmRFbmdpbmUoKVwiICpuZ0lmPVwiIXRyaWdnZXI7IGVsc2Ugc3RvcF9idXR0b25cIj5MdW5jaCBLZXlib2FyZCBDb3JlPC9idXR0b24+XG4gIDxuZy10ZW1wbGF0ZSAjc3RvcF9idXR0b24+XG4gICAgPGJ1dHRvbiBtYXQtcmFpc2VkLWJ1dHRvbiBjb2xvcj1cImFjY2VudFwiIChjbGljayk9XCJsdW5jaEtleWJvYXJkRW5naW5lKClcIj5TdG9wIEtleWJvYXJkIENvcmU8L2J1dHRvbj5cbiAgPC9uZy10ZW1wbGF0ZT5cbjwvZGl2PiIsIjxhcHAtYXBtLWx1bmNoZXI+PC9hcHAtYXBtLWx1bmNoZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0NFO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBMEM7TUFBQTtNQUFBO0lBQUE7SUFBMUM7RUFBQSx1REFBQTsyQkFBQSxrREFBQTtNQUFBO01BQUEsMENBQUE7TUFBQSwyQ0FBNkc7O1FBQW5GO1FBQTFCLFdBQTBCLFNBQTFCOztRQUFBO1FBQUEsV0FBQSxTQUFBOzs7O29CQUMwQiw4Q0FDeEI7TUFBQTtVQUFBO01BQUE7UUFBQTtRQUFBO1FBQXlDO1VBQUE7VUFBQTtRQUFBO1FBQXpDO01BQUEsdURBQUE7TUFBQSx5RUFBQTtNQUFBO3lCQUFBLDRDQUFBO01BQUE7TUFBeUUsOENBQTJCO1VBQUE7SUFBMUU7SUFBMUIsV0FBMEIsU0FBMUI7O0lBQUE7SUFBQSxXQUFBLFNBQUE7Ozs7b0JBSEo7TUFBQTtNQUFBLGlFQUFBO01BQUE7VUFBQSxpQ0FBQTtNQUFBO1VBQUEseUJBQXlFLDRDQUN2RTthQUFBO2FBQUE7VUFBQSx5REFBeUk7VUFBQSx5QkFDekk7VUFBQSwwQ0FFYztVQUFBOztJQUpYO0lBQUwsV0FBSyxTQUFMO0lBQXVCO0lBQXZCLFdBQXVCLFNBQXZCO0lBQzRFO0lBQUE7SUFBMUUsV0FBMEUsbUJBQTFFOzs7O29CQ0RGO01BQUE7aUNBQUEsVUFBQTtNQUFBOzs7In0=
