/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.module';
import * as i2 from '../../../src/app/app.component';
import * as i3 from './app.component.ngfactory';
import * as i4 from '@angular/common';
import * as i5 from '@angular/platform-browser';
import * as i6 from '@angular/animations/browser';
import * as i7 from '@angular/platform-browser/animations';
import * as i8 from '../../../src/app/core/engine/keyboard-engine.service';
import * as i9 from '../../../src/app/core/engine/timer-engine.service';
import * as i10 from '../../../src/app/core/apm-test/apm-test.service';
import * as i11 from '../../../src/app/core/keyboard/keyboard-mapping.service';
import * as i12 from '@angular/animations';
import * as i13 from '@angular/cdk/bidi';
import * as i14 from '@angular/material/icon';
import * as i15 from '@angular/http';
import * as i16 from '@angular/cdk/platform';
import * as i17 from '@angular/cdk/a11y';
import * as i18 from '@angular/cdk/scrolling';
import * as i19 from '@angular/cdk/overlay';
import * as i20 from '@angular/material/core';
import * as i21 from '@angular/flex-layout/media-query/match-media';
import * as i22 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as i23 from '@angular/flex-layout/media-query/breakpoints/break-points';
import * as i24 from '@angular/flex-layout/media-query/media-monitor';
import * as i25 from '@angular/flex-layout/media-query/observable-media-service';
import * as i26 from '@ngrx/store';
import * as i27 from '../../../src/app/core/reducers/bo.reducer';
import * as i28 from '../../../src/app/core/reducers/keyboard.reducer';
import * as i29 from '../../../src/app/core/core.module';
import * as i30 from '@angular/material/button';
import * as i31 from '@angular/material/grid-list';
import * as i32 from '@angular/material/toolbar';
import * as i33 from '@angular/cdk/portal';
import * as i34 from '@angular/material/sidenav';
import * as i35 from '@angular/material/card';
import * as i36 from '@angular/material/form-field';
import * as i37 from '@angular/material/input';
import * as i38 from '../../../src/app/apm-material/apm-material.module';
import * as i39 from '@angular/flex-layout/media-query/_module';
import * as i40 from '@angular/flex-layout/flexbox/_module';
import * as i41 from '../../../src/app/shared/shared.module';
import * as i42 from '../../../src/app/apm/apm-exercice/apm-exercice.module';
import * as i43 from '../../../src/app/apm/apm.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i4.NgLocalization,
              i4.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
              i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵl,([] as any[])),i0.ɵmpd(4608,i5.DomSanitizer,i5.ɵe,[i4.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i5.DomSanitizer]),i0.ɵmpd(4608,
              i5.HAMMER_GESTURE_CONFIG,i5.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i5.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i5.ɵDomEventsPlugin(p0_0),new i5.ɵKeyEventsPlugin(p1_0),
                    new i5.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i4.DOCUMENT,i4.DOCUMENT,i4.DOCUMENT,i5.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i5.EventManager,i5.EventManager,[i5.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i5.ɵDomSharedStylesHost,i5.ɵDomSharedStylesHost,[i4.DOCUMENT]),
          i0.ɵmpd(4608,i5.ɵDomRendererFactory2,i5.ɵDomRendererFactory2,[i5.EventManager,
              i5.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i6.AnimationDriver,i7.ɵc,([] as any[])),
          i0.ɵmpd(5120,i6.ɵAnimationStyleNormalizer,i7.ɵd,([] as any[])),i0.ɵmpd(4608,
              i6.ɵAnimationEngine,i7.ɵb,[i6.AnimationDriver,i6.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i7.ɵe,[i5.ɵDomRendererFactory2,i6.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i5.ɵSharedStylesHost,(null as any),[i5.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i5.Meta,
              i5.Meta,[i4.DOCUMENT]),i0.ɵmpd(4608,i5.Title,i5.Title,[i4.DOCUMENT]),
          i0.ɵmpd(4608,i8.KeyboardEngineService,i8.KeyboardEngineService,([] as any[])),
          i0.ɵmpd(4608,i9.TimerEngineService,i9.TimerEngineService,([] as any[])),
          i0.ɵmpd(4608,i10.ApmTestService,i10.ApmTestService,[i8.KeyboardEngineService,
              i9.TimerEngineService]),i0.ɵmpd(4608,i11.KeyboardMappingService,i11.KeyboardMappingService,
              ([] as any[])),i0.ɵmpd(4608,i12.AnimationBuilder,i7.ɵBrowserAnimationBuilder,
              [i0.RendererFactory2,i5.DOCUMENT]),i0.ɵmpd(6144,i13.DIR_DOCUMENT,(null as any),
              [i5.DOCUMENT]),i0.ɵmpd(4608,i13.Directionality,i13.Directionality,[[2,
              i13.DIR_DOCUMENT]]),i0.ɵmpd(5120,i14.MatIconRegistry,i14.ICON_REGISTRY_PROVIDER_FACTORY,
              [[3,i14.MatIconRegistry],[2,i15.Http],i5.DomSanitizer]),i0.ɵmpd(4608,
              i16.Platform,i16.Platform,([] as any[])),i0.ɵmpd(4608,i17.InteractivityChecker,
              i17.InteractivityChecker,[i16.Platform]),i0.ɵmpd(4608,i17.FocusTrapFactory,
              i17.FocusTrapFactory,[i17.InteractivityChecker,i16.Platform,i0.NgZone]),
          i0.ɵmpd(136192,i17.AriaDescriber,i17.ARIA_DESCRIBER_PROVIDER_FACTORY,[[3,
              i17.AriaDescriber],i16.Platform]),i0.ɵmpd(5120,i17.LiveAnnouncer,i17.LIVE_ANNOUNCER_PROVIDER_FACTORY,
              [[3,i17.LiveAnnouncer],[2,i17.LIVE_ANNOUNCER_ELEMENT_TOKEN],i16.Platform]),
          i0.ɵmpd(5120,i17.FocusMonitor,i17.FOCUS_MONITOR_PROVIDER_FACTORY,[[3,i17.FocusMonitor],
              i0.NgZone,i16.Platform]),i0.ɵmpd(5120,i18.ScrollDispatcher,i18.SCROLL_DISPATCHER_PROVIDER_FACTORY,
              [[3,i18.ScrollDispatcher],i0.NgZone,i16.Platform]),i0.ɵmpd(5120,i18.ViewportRuler,
              i18.VIEWPORT_RULER_PROVIDER_FACTORY,[[3,i18.ViewportRuler],i16.Platform,
                  i0.NgZone,i18.ScrollDispatcher]),i0.ɵmpd(4608,i19.ScrollStrategyOptions,
              i19.ScrollStrategyOptions,[i18.ScrollDispatcher,i18.ViewportRuler]),
          i0.ɵmpd(5120,i19.OverlayContainer,i19.ɵa,[[3,i19.OverlayContainer]]),i0.ɵmpd(4608,
              i19.ɵf,i19.ɵf,[i18.ViewportRuler]),i0.ɵmpd(4608,i19.Overlay,i19.Overlay,
              [i19.ScrollStrategyOptions,i19.OverlayContainer,i0.ComponentFactoryResolver,
                  i19.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i19.ɵc,
              i19.ɵd,[i19.Overlay]),i0.ɵmpd(4608,i20.ErrorStateMatcher,i20.ErrorStateMatcher,
              ([] as any[])),i0.ɵmpd(4608,i21.MatchMedia,i21.MatchMedia,[i0.NgZone]),
          i0.ɵmpd(4608,i22.BreakPointRegistry,i22.BreakPointRegistry,[i23.BREAKPOINTS]),
          i0.ɵmpd(4608,i24.MediaMonitor,i24.MediaMonitor,[i22.BreakPointRegistry,i21.MatchMedia]),
          i0.ɵmpd(4608,i25.ObservableMedia,i25.MediaService,[i21.MatchMedia,i22.BreakPointRegistry]),
          i0.ɵmpd(135680,i26.State,i26.State,[i26.ActionsSubject,i26.ReducerObservable,
              i26.ScannedActionsSubject,i26.INITIAL_STATE]),i0.ɵmpd(6144,i26.StateObservable,
              (null as any),[i26.State]),i0.ɵmpd(4608,i26.Store,i26.Store,[i26.StateObservable,
              i26.ActionsSubject,i26.ReducerManager]),i0.ɵmpd(512,i4.CommonModule,
              i4.CommonModule,([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i5.ɵa,([] as any[])),
          i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any) => {
            return [i5.ɵc(p0_0,p0_1)];
          },[[2,i5.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i5.BrowserModule,i5.BrowserModule,[[3,i5.BrowserModule]]),i0.ɵmpd(131584,
              i26.ActionsSubject,i26.ActionsSubject,([] as any[])),i0.ɵmpd(2048,i26.ReducerManagerDispatcher,
              (null as any),[i26.ActionsSubject]),i0.ɵmpd(256,i26._INITIAL_STATE,(undefined as any),
              ([] as any[])),i0.ɵmpd(1024,i26.INITIAL_STATE,i26._initialStateFactory,
              [i26._INITIAL_STATE]),i0.ɵmpd(256,i26._INITIAL_REDUCERS,{bo:i27.BoReducer,
              keyboard:i28.KeyboardReducer},([] as any[])),i0.ɵmpd(2048,i26._STORE_REDUCERS,
              (null as any),[i26._INITIAL_REDUCERS]),i0.ɵmpd(1024,i26.INITIAL_REDUCERS,
              i26._createStoreReducers,[i0.Injector,i26._INITIAL_REDUCERS,i26._STORE_REDUCERS]),
          i0.ɵmpd(256,i26._REDUCER_FACTORY,i26.combineReducers,([] as any[])),i0.ɵmpd(256,
              i26.META_REDUCERS,([] as any[]),([] as any[])),i0.ɵmpd(1024,i26.REDUCER_FACTORY,
              i26.createReducerFactory,[i26._REDUCER_FACTORY,i26.META_REDUCERS]),i0.ɵmpd(131584,
              i26.ReducerManager,i26.ReducerManager,[i26.ReducerManagerDispatcher,
                  i26.INITIAL_STATE,i26.INITIAL_REDUCERS,i26.REDUCER_FACTORY]),i0.ɵmpd(2048,
              i26.ReducerObservable,(null as any),[i26.ReducerManager]),i0.ɵmpd(131584,
              i26.ScannedActionsSubject,i26.ScannedActionsSubject,([] as any[])),i0.ɵmpd(512,
              i26.StoreRootModule,i26.StoreRootModule,[i26.ActionsSubject,i26.ReducerObservable,
                  i26.ScannedActionsSubject]),i0.ɵmpd(512,i29.CoreModule,i29.CoreModule,
              ([] as any[])),i0.ɵmpd(512,i7.BrowserAnimationsModule,i7.BrowserAnimationsModule,
              ([] as any[])),i0.ɵmpd(512,i20.CompatibilityModule,i20.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(512,i13.BidiModule,i13.BidiModule,([] as any[])),
          i0.ɵmpd(256,i20.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i20.MatCommonModule,
              i20.MatCommonModule,[[2,i20.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i14.MatIconModule,
              i14.MatIconModule,([] as any[])),i0.ɵmpd(512,i16.PlatformModule,i16.PlatformModule,
              ([] as any[])),i0.ɵmpd(512,i20.MatRippleModule,i20.MatRippleModule,([] as any[])),
          i0.ɵmpd(512,i17.A11yModule,i17.A11yModule,([] as any[])),i0.ɵmpd(512,i30.MatButtonModule,
              i30.MatButtonModule,([] as any[])),i0.ɵmpd(512,i20.MatLineModule,i20.MatLineModule,
              ([] as any[])),i0.ɵmpd(512,i31.MatGridListModule,i31.MatGridListModule,
              ([] as any[])),i0.ɵmpd(512,i32.MatToolbarModule,i32.MatToolbarModule,
              ([] as any[])),i0.ɵmpd(512,i33.PortalModule,i33.PortalModule,([] as any[])),
          i0.ɵmpd(512,i18.ScrollDispatchModule,i18.ScrollDispatchModule,([] as any[])),
          i0.ɵmpd(512,i19.OverlayModule,i19.OverlayModule,([] as any[])),i0.ɵmpd(512,
              i34.MatSidenavModule,i34.MatSidenavModule,([] as any[])),i0.ɵmpd(512,
              i35.MatCardModule,i35.MatCardModule,([] as any[])),i0.ɵmpd(512,i36.MatFormFieldModule,
              i36.MatFormFieldModule,([] as any[])),i0.ɵmpd(512,i37.MatInputModule,
              i37.MatInputModule,([] as any[])),i0.ɵmpd(512,i38.ApmMaterialModule,
              i38.ApmMaterialModule,([] as any[])),i0.ɵmpd(512,i39.MediaQueriesModule,
              i39.MediaQueriesModule,([] as any[])),i0.ɵmpd(512,i40.FlexLayoutModule,
              i40.FlexLayoutModule,([] as any[])),i0.ɵmpd(512,i41.SharedModule,i41.SharedModule,
              ([] as any[])),i0.ɵmpd(512,i42.ApmExerciceModule,i42.ApmExerciceModule,
              ([] as any[])),i0.ɵmpd(512,i43.ApmModule,i43.ApmModule,([] as any[])),
          i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),i0.ɵmpd(256,i23.BREAKPOINTS,
              i23.RAW_DEFAULTS,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3Zhci93d3cvYXBtL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy92YXIvd3d3L2FwbS9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
