/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/apm-material/apm-material.module';
import * as i2 from '@angular/cdk/bidi';
import * as i3 from '@angular/platform-browser';
import * as i4 from '@angular/material/icon';
import * as i5 from '@angular/http';
import * as i6 from '@angular/common';
import * as i7 from '@angular/cdk/platform';
import * as i8 from '@angular/cdk/a11y';
import * as i9 from '@angular/cdk/scrolling';
import * as i10 from '@angular/cdk/overlay';
import * as i11 from '@angular/material/core';
import * as i12 from '@angular/material/button';
import * as i13 from '@angular/material/grid-list';
import * as i14 from '@angular/material/toolbar';
import * as i15 from '@angular/cdk/portal';
import * as i16 from '@angular/material/sidenav';
import * as i17 from '@angular/material/card';
import * as i18 from '@angular/material/form-field';
import * as i19 from '@angular/material/input';
export const ApmMaterialModuleNgFactory:i0.NgModuleFactory<i1.ApmMaterialModule> = i0.ɵcmf(i1.ApmMaterialModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(6144,
          i2.DIR_DOCUMENT,(null as any),[i3.DOCUMENT]),i0.ɵmpd(4608,i2.Directionality,
          i2.Directionality,[[2,i2.DIR_DOCUMENT]]),i0.ɵmpd(5120,i4.MatIconRegistry,
          i4.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i4.MatIconRegistry],[2,i5.Http],i3.DomSanitizer]),
          i0.ɵmpd(4608,i6.NgLocalization,i6.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i7.Platform,i7.Platform,([] as any[])),i0.ɵmpd(4608,i8.InteractivityChecker,
              i8.InteractivityChecker,[i7.Platform]),i0.ɵmpd(4608,i8.FocusTrapFactory,
              i8.FocusTrapFactory,[i8.InteractivityChecker,i7.Platform,i0.NgZone]),
          i0.ɵmpd(136192,i8.AriaDescriber,i8.ARIA_DESCRIBER_PROVIDER_FACTORY,[[3,i8.AriaDescriber],
              i7.Platform]),i0.ɵmpd(5120,i8.LiveAnnouncer,i8.LIVE_ANNOUNCER_PROVIDER_FACTORY,
              [[3,i8.LiveAnnouncer],[2,i8.LIVE_ANNOUNCER_ELEMENT_TOKEN],i7.Platform]),
          i0.ɵmpd(5120,i8.FocusMonitor,i8.FOCUS_MONITOR_PROVIDER_FACTORY,[[3,i8.FocusMonitor],
              i0.NgZone,i7.Platform]),i0.ɵmpd(5120,i9.ScrollDispatcher,i9.SCROLL_DISPATCHER_PROVIDER_FACTORY,
              [[3,i9.ScrollDispatcher],i0.NgZone,i7.Platform]),i0.ɵmpd(5120,i9.ViewportRuler,
              i9.VIEWPORT_RULER_PROVIDER_FACTORY,[[3,i9.ViewportRuler],i7.Platform,
                  i0.NgZone,i9.ScrollDispatcher]),i0.ɵmpd(4608,i10.ScrollStrategyOptions,
              i10.ScrollStrategyOptions,[i9.ScrollDispatcher,i9.ViewportRuler]),i0.ɵmpd(5120,
              i10.OverlayContainer,i10.ɵa,[[3,i10.OverlayContainer]]),i0.ɵmpd(4608,
              i10.ɵf,i10.ɵf,[i9.ViewportRuler]),i0.ɵmpd(4608,i10.Overlay,i10.Overlay,
              [i10.ScrollStrategyOptions,i10.OverlayContainer,i0.ComponentFactoryResolver,
                  i10.ɵf,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i10.ɵc,
              i10.ɵd,[i10.Overlay]),i0.ɵmpd(4608,i11.ErrorStateMatcher,i11.ErrorStateMatcher,
              ([] as any[])),i0.ɵmpd(512,i11.CompatibilityModule,i11.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(512,i2.BidiModule,i2.BidiModule,([] as any[])),
          i0.ɵmpd(256,i11.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i11.MatCommonModule,
              i11.MatCommonModule,[[2,i11.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i4.MatIconModule,
              i4.MatIconModule,([] as any[])),i0.ɵmpd(512,i6.CommonModule,i6.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i7.PlatformModule,i7.PlatformModule,([] as any[])),
          i0.ɵmpd(512,i11.MatRippleModule,i11.MatRippleModule,([] as any[])),i0.ɵmpd(512,
              i8.A11yModule,i8.A11yModule,([] as any[])),i0.ɵmpd(512,i12.MatButtonModule,
              i12.MatButtonModule,([] as any[])),i0.ɵmpd(512,i11.MatLineModule,i11.MatLineModule,
              ([] as any[])),i0.ɵmpd(512,i13.MatGridListModule,i13.MatGridListModule,
              ([] as any[])),i0.ɵmpd(512,i14.MatToolbarModule,i14.MatToolbarModule,
              ([] as any[])),i0.ɵmpd(512,i15.PortalModule,i15.PortalModule,([] as any[])),
          i0.ɵmpd(512,i9.ScrollDispatchModule,i9.ScrollDispatchModule,([] as any[])),
          i0.ɵmpd(512,i10.OverlayModule,i10.OverlayModule,([] as any[])),i0.ɵmpd(512,
              i16.MatSidenavModule,i16.MatSidenavModule,([] as any[])),i0.ɵmpd(512,
              i17.MatCardModule,i17.MatCardModule,([] as any[])),i0.ɵmpd(512,i18.MatFormFieldModule,
              i18.MatFormFieldModule,([] as any[])),i0.ɵmpd(512,i19.MatInputModule,
              i19.MatInputModule,([] as any[])),i0.ɵmpd(512,i1.ApmMaterialModule,i1.ApmMaterialModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3Zhci93d3cvYXBtL3NyYy9hcHAvYXBtLW1hdGVyaWFsL2FwbS1tYXRlcmlhbC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vdmFyL3d3dy9hcG0vc3JjL2FwcC9hcG0tbWF0ZXJpYWwvYXBtLW1hdGVyaWFsLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
