/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './keyboard.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../node_modules/@angular/material/grid-list/typings/index.ngfactory';
import * as i3 from '@angular/material/core';
import * as i4 from '@angular/material/grid-list';
import * as i5 from '@angular/cdk/bidi';
import * as i6 from '@angular/common';
import * as i7 from '../../../../../../src/app/apm/apm-exercice/keyboard/keyboard.component';
import * as i8 from '../../../../../../src/app/core/apm-test/apm-test.service';
const styles_KeyboardComponent:any[] = [i0.styles];
export const RenderType_KeyboardComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_KeyboardComponent,data:{}});
function View_KeyboardComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),3,'mat-grid-tile',
      [['class','mat-grid-tile']],[[4,'background',(null as any)]],(null as any),(null as any),
      i2.View_MatGridTile_0,i2.RenderType_MatGridTile)),i1.ɵdid(1,16384,(null as any),
      0,i3.MatPrefixRejector,([] as any[]),(null as any),(null as any)),i1.ɵdid(2,
      49152,[[1,4]],0,i4.MatGridTile,[i1.Renderer2,i1.ElementRef],{rowspan:[0,'rowspan'],
          colspan:[1,'colspan']},(null as any)),(_l()(),i1.ɵted(3,0,['\n    ','\n  ']))],
      (_ck,_v) => {
        const currVal_1:any = _v.context.$implicit.rows;
        const currVal_2:any = _v.context.$implicit.cols;
        _ck(_v,2,0,currVal_1,currVal_2);
      },(_ck,_v) => {
        const currVal_0:any = _v.context.$implicit.color;
        _ck(_v,0,0,currVal_0);
        const currVal_3:any = _v.context.$implicit.text;
        _ck(_v,3,0,currVal_3);
      });
}
export function View_KeyboardComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),7,'mat-grid-list',
      [['class','mat-grid-list'],['cols','4'],['rowHeight','100px']],(null as any),
      (null as any),(null as any),i2.View_MatGridList_0,i2.RenderType_MatGridList)),
      i1.ɵdid(1,16384,(null as any),0,i3.MatPrefixRejector,([] as any[]),(null as any),
          (null as any)),i1.ɵdid(2,2211840,(null as any),1,i4.MatGridList,[i1.Renderer2,
          i1.ElementRef,[2,i5.Directionality]],{cols:[0,'cols'],rowHeight:[1,'rowHeight']},
          (null as any)),i1.ɵqud(603979776,1,{_tiles:1}),(_l()(),i1.ɵted(-1,0,['\n  '])),
      (_l()(),i1.ɵand(16777216,(null as any),0,1,(null as any),View_KeyboardComponent_1)),
      i1.ɵdid(6,802816,(null as any),0,i6.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,
          i1.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i1.ɵted(-1,
          0,['\n']))],(_ck,_v) => {
    var _co:i7.KeyboardComponent = _v.component;
    const currVal_0:any = '4';
    const currVal_1:any = '100px';
    _ck(_v,2,0,currVal_0,currVal_1);
    const currVal_2:any = _co.keyboard;
    _ck(_v,6,0,currVal_2);
  },(null as any));
}
export function View_KeyboardComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-apm-keyboard',
      ([] as any[]),(null as any),(null as any),(null as any),View_KeyboardComponent_0,
      RenderType_KeyboardComponent)),i1.ɵdid(1,114688,(null as any),0,i7.KeyboardComponent,
      [i8.ApmTestService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const KeyboardComponentNgFactory:i1.ComponentFactory<i7.KeyboardComponent> = i1.ɵccf('app-apm-keyboard',
    i7.KeyboardComponent,View_KeyboardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL3Zhci93d3cvYXBtL3NyYy9hcHAvYXBtL2FwbS1leGVyY2ljZS9rZXlib2FyZC9rZXlib2FyZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vdmFyL3d3dy9hcG0vc3JjL2FwcC9hcG0vYXBtLWV4ZXJjaWNlL2tleWJvYXJkL2tleWJvYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL3Zhci93d3cvYXBtL3NyYy9hcHAvYXBtL2FwbS1leGVyY2ljZS9rZXlib2FyZC9rZXlib2FyZC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL3Zhci93d3cvYXBtL3NyYy9hcHAvYXBtL2FwbS1leGVyY2ljZS9rZXlib2FyZC9rZXlib2FyZC5jb21wb25lbnQudHMuS2V5Ym9hcmRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8bWF0LWdyaWQtbGlzdCBjb2xzPVwiNFwiIHJvd0hlaWdodD1cIjEwMHB4XCI+XG4gIDxtYXQtZ3JpZC10aWxlXG4gICAgICAqbmdGb3I9XCJsZXQga2V5IG9mIGtleWJvYXJkXCJcbiAgICAgIFtjb2xzcGFuXT1cImtleS5jb2xzXCJcbiAgICAgIFtyb3dzcGFuXT1cImtleS5yb3dzXCJcbiAgICAgIFtzdHlsZS5iYWNrZ3JvdW5kXT1cImtleS5jb2xvclwiPlxuICAgIHt7a2V5LnRleHR9fVxuICA8L21hdC1ncmlkLXRpbGU+XG48L21hdC1ncmlkLWxpc3Q+IiwiPGFwcC1hcG0ta2V5Ym9hcmQ+PC9hcHAtYXBtLWtleWJvYXJkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNDRTtNQUFBO3FEQUFBLFVBQUE7TUFBQSx5RUFBQTtNQUFBO1VBQUEsc0NBSW1DOztRQUQvQjtRQURBO1FBRkosV0FHSSxVQURBLFNBRko7O1FBSUk7UUFKSixXQUlJLFNBSko7UUFJbUM7UUFBQTs7OztvQkFMckM7TUFBQTtNQUFBO2FBQUE7VUFBQSxzQkFBQTt3QkFBQTtVQUFBLCtDQUEwQztNQUN4QzthQUFBOzRCQUFBLHlDQU1nQjtVQUFBOztJQVBIO0lBQVM7SUFBeEIsV0FBZSxVQUFTLFNBQXhCO0lBRU07SUFESixXQUNJLFNBREo7Ozs7b0JDREY7TUFBQTtrQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
