/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.luncher-box[_ngcontent-%COMP%]{\n    margin: 0;\n    width: 100%;\n    height: 60%;\n}'];
//# sourceMappingURL=luncher.component.css.shim.ngstyle.js.map